---
- name: Install necessary packages
  apt:
    name: "{{ packages }}"
    state: latest
  vars:
    packages:
    - wireless-regdb
    - iw
    - crda

- name: Set regulatory domain
  lineinfile: dest=/etc/default/crda regexp="REGDOMAIN=.*" line="REGDOMAIN={{ crda_domain_code }}"
  notify: reboot
